# Microsoft Visual C++ 2013 compiler

CC=cmd /K msvc-cl.bat
COMPILER=Visual C++
CFLAGS=
LFLAGS=
SEP=/
SAD_OUT_FLAG=-Febin/sad
SAD_TEST_OUT_FLAG=-Febin/sad-test
SAD_RUN=bin/sad
SAD_TEST_RUN=bin/sad-test

include Makefile.base
