# LCC-Win compiler

CC=lc
COMPILER=LCC-Win
CFLAGS=-A -shadows -unused
LFLAGS=
SEP=\\
SAD_OUT_FLAG=-o bin/sad
SAD_TEST_OUT_FLAG=-o bin/sad-test
SAD_RUN=bin/sad
SAD_TEST_RUN=bin/sad-test

include Makefile.base
