# Borland C++ 5.5 compiler

CC=bcc32
CFLAGS=-q -Q -w -w! -w-8004 -w-8073 -A -tWC -v -O2 -IC:/Borland/BCC55/Include -nbin
LFLAGS=-LC:/Borland/BCC55/Lib
SEP=/
SAD_OUT_FLAG=-obin/sad
SAD_TEST_OUT_FLAG=-obin/sad-test

include Makefile.base
